import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalStyle } from "./styles/globalsStyle";
import Providers from "./provider";
import StyledComponentsRegistry from "./registry";
import ModalsProvider from "@/lib/context/modalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <GlobalStyle />
            <body suppressHydrationWarning={true} className={inter.className}>
                <Providers>
                    <ModalsProvider>
                        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
                    </ModalsProvider>
                </Providers>
            </body>
        </html>
    );
}
